# ===== Global (å…±é€š) =====
format = "$all"

[character]
format = "[âš¡ï¸](bold green) "
success_symbol = "[âš¡ï¸](bold green) "
error_symbol = "[âš¡ï¸](bold red) "

[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
truncation_length = 4
truncate_to_repo = false
truncation_symbol = "â€¦/"

[git_status]
disabled = true

[hostname]
disabled = true

[time]
disabled = false
time_format = "%Y-%m-%d %H:%M"
utc_time_offset = "+9"

[username]
disabled = true

[cmd_duration]
min_time = 500
format = "[$duration]($style) "

[git_branch]
symbol = "ğŸŒ± "
truncation_length = 4
truncation_symbol = ""
